spring.application.name=uiktp-backend

# H2 in-memory database
#spring.datasource.url=jdbc:h2:mem:devdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/uiktp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
jwt_secret=a-string-secret-at-least-256-bits-long

# URLS
urls.weather-api-url=https://api.open-meteo.com/v1

# TIMES
irrigation.api.base-url=http://localhost:8000